---

- name: Install Apache on remote host
  hosts: myhosts
  become: true
  tasks:

  - name: Update repository index
    apt:
      update_cache: yes

  - name: Instal Apache on remote host
    apt:
      name: apache2
      state: latest

  - name: Add php support for Apache
    apt:
      name: libapache2-mod-php
      state: latest


