- name: Install apt on Ubuntu host if not installed
  hosts: myhosts
  become: true
  tasks:
    - name: Check if APT is installed
      ansible.builtin.command: dpkg-query -l bashtop
      register: apt_check
      ignore_errors: yes

    - name: Print message if APT is already installed
      debug:
        msg: "bashtop is already installed"
      when: apt_check.rc == 0
      
    - name: Install APT if not installed
      ansible.builtin.apt:
        name: bashtop
        state: present
      when: apt_check.rc != 0
    
    - name: Print message after APT is installed
      debug:
        msg: "bashtop was just installed"
      when: apt_check.rc != 0



